data:
  dataset:
    train_path: /m/liyz/MedQA-workspace/rawdata/es_result_0713_production_idx/v6/v6_train.json.310000
    dev_path: /m/liyz/MedQA-workspace/rawdata/es_result_0713_production_idx/v6/v6_dev.json.13441
    test_path: /m/liyz/MedQA-workspace/rawdata/es_result_0713_production_idx/v6/v6_test.json.600
  dataset_h5: /m/liyz/MedQA-workspace/v1.0/data/v6_31w_with297k_embedding_maxcontentlen200_withlogic.h5  #保存预处理的数据，embedding，w2id等
  ignore_max_len: 200 # in train data, context token len > ignore_max_len will be dropped
  ignore_max_ques_ans_len: 100

  embedding_path: data/corpus_embedding_297k_200.txt   # data/glove.840B.300d.zip
  vocabulary_path: data/vocabulary

  model_path: checkpoint/pkumi2_2018-07-17-00_50_30_v6data_scratch_lr=1e-4_model_weight.pt
  model_weight_dir: checkpoint/
  checkpoint_path: checkpoint/

model:
  encoder:
    word_embedding_size: 200

global:
  random_seed: 123
  model: SeaReader_5c   #SeaReader
   #match-lstm+ # 'match-lstm', 'match-lstm+', 'r-net' or 'base'. Note that 'base' model is customized by base_model.yaml

train:
  continue: False # 默认是不是继续上次训练
  keep_embedding: True # 是否保留weight里的embedding
  batch_size: 150  #最好是5的倍数，便于计算准确率
  valid_batch_size: 150 #default 32
  test_batch_size: 150
  epoch: 100
  enable_cuda: True

  optimizer: 'adam'  # adam, sgd, adamax, adadelta(default is adamax)
  learning_rate: 0.001  # only for sgd
  eps: 1e-6
  clip_grad_norm: 5

test:
  model: SeaReader
  test_batch_size: 200
  enable_cuda: True
  keep_embedding: True # 是否保留weight里的embedding
  dataset_h5: data/v6_31w_with297k_embedding_maxcontentlen200_withlogic.h5  #保存预处理的数据，embedding，w2id等
  model_path: checkpoint/panda2_2018-07-17-13_58_53_continue_pkumi2_v6data_lr=-4_model_weight.pt
  output_file_path: 'result/'

